### ISSUE TITLE
Nodegit: https a ssh credentials

### ISSUE THREAD

**Issue by FilipChalupa** [Onset/git-latex#24]
Vyřešit problém, že server zamítá spojení kvůli špatným credentials.

**Comment by FilipChalupa** [comment]
GitKraken to nějak vyřešil.

**Comment by kalvotom** [comment]
S https repozitářem chybka:

```
electron-react-boilerplate: ../vendor/libgit2/src/transports/http.c:377: int on_headers_complete(http_parser *): Assertion `t->cred' failed.
```

**Comment by FilipChalupa** [comment]
Problémy způsoboval minimálně na Windows Webpack, protože zahazoval některé funkce z Nodegitu.
